spring.application.name=primerProyecto

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# URL con sslmode=require obligatorio para Supabase
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require

# Credenciales
spring.datasource.username=postgres.whvtptjpxidvblsmitgj
spring.datasource.password=9%21n29%2Fy2%26es8%25Jj

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

